# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  tests:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: mv .env.example .env
      - run: sudo apt update
      - run: sudo apt install libpng-dev
      - run: sudo docker-php-ext-install zip bcmath gd
      - run: composer install -n --prefer-dist
      - run: touch database/database.sqlite
      - run: mkdir test_results/

      - run: ./vendor/bin/phpunit --coverage-xml test_results/

      - store_test_results:
          path: test_results/
  dusk:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: mv .env.example .env
      - run: sudo apt update
      - run: sudo apt install libpng-dev
      - run: sudo docker-php-ext-install zip bcmath gd
      - run: composer install -n --prefer-dist
      - run: npm install
      - run: touch database/database.sqlite

      - run:
          command: php artisan serve
          background: true

      - run: php artisan dusk:chrome-driver
      - run: php artisan dusk
workflows:
  version: 2
  laravel-tests:
    jobs:
      - tests
      - dusk
